
default: &default
  adapter: postgresql
  encoding: <%= ENV['DBENCODING'] %>
  pool: <%= ENV['DBPOOL'] %>
  username: <%= ENV['DBUSER'] %>
  password: <%= ENV['DBPASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DBDEV'] %>

test:
  <<: *default
  database: <%= ENV['DBTEST'] %>

production:
  <<: *default
  database: <%= ENV['DBPROD'] %>
